language: php

php:
  - 5.6
  - 7.0
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - composer install --dev

script:
  - vendor/bin/phpunit

after_success:
  - travis_retry php vendor/bin/coveralls -v
